# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.tests(
    ignoreList=["Provenance_1.py", "testExceptions.py", 
                "testMySQLConfigurator.py", "testSharedData.py"]
)
